### ISSUE TITLE
Request for connect 

### ISSUE THREAD

**Issue by ManiiG** [waciumawanjohi/computer-science-orig#6]
Hello, I wanted to start my journey with OSSU for a self taught CS course.
Do I require to enroll somewhere?
Should I just begin with the enlisted module?

Requesting for guidance please.

Regards

**Comment by waciumawanjohi** [comment]
@ManiiG Start by reading the official curriculum. You can see that my repo is a fork of the official repo here: https://github.com/ossu/computer-science

A slightly easier to read version is cs.ossu.dev

Those pages include a link to the OSSU Discord server, where learners gather to talk and discuss. I also recommend reading the FAQ on the Discord server.

- Do I require to enroll somewhere?
  - No
- Should I just begin with the enlisted module?
  - Yes, start at the beginning and work your way through.

**Comment by ManiiG** [comment]
Thank you 🙏
